# Generated by Django 4.2.4 on 2023-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kliniks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klinik',
            name='nama_klinik',
            field=models.CharField(max_length=16),
        ),
    ]
