# Generated by Django 4.2.4 on 2023-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kliniks', '0002_alter_klinik_nama_klinik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klinik',
            name='nama_klinik',
            field=models.CharField(max_length=255),
        ),
    ]
