# Generated by Django 4.2.4 on 2023-08-15 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relasidokterkliniks', '0002_rename_id_dokter_relasidokterklinik_dokter_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relasidokterklinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('url_image', models.TextField()),
                ('relasidokterklinik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relasidokterklinik', to='relasidokterkliniks.relasidokterklinik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user')),
            ],
        ),
    ]
