# Generated by Django 4.2.4 on 2023-09-04 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('pemeriksaans', '0006_screening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='user',
        ),
        migrations.AddField(
            model_name='screening',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='users.user'),
            preserve_default=False,
        ),
    ]
