# Generated by Django 4.2.4 on 2023-09-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemeriksaans', '0007_remove_screening_user_screening_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='user_id',
            new_name='user',
        ),
    ]
