# Generated by Django 4.2.4 on 2023-09-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemeriksaans', '0009_screening_scan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='status',
            field=models.TextField(default='pending'),
        ),
        migrations.AddField(
            model_name='screening',
            name='status',
            field=models.TextField(default='pending'),
        ),
    ]
