# Generated by Django 4.2.4 on 2023-08-14 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kliniks', '0002_alter_klinik_nama_klinik'),
        ('dokters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relasidokterklinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokter', to='dokters.dokter')),
                ('id_klinik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klinik', to='kliniks.klinik')),
            ],
        ),
    ]
